package com.coaching.saas.controller;

import com.coaching.saas.api.ApiModels.*;
import com.coaching.saas.model.DocumentModels.*;
import com.coaching.saas.model.Enums;
import com.coaching.saas.repo.*;
import com.coaching.saas.security.TenantContext;
import com.coaching.saas.service.*;
import jakarta.validation.Valid;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.HttpStatus;
import org.springframework.web.server.ResponseStatusException;
import java.time.*; import java.util.*; import java.util.stream.Collectors;

@RestController @RequestMapping("/api")
public class ManagementController {
 final StudentRepository students; final TeacherRepository teachers; final BatchRepository batches; final SessionRepository sessions;
 final AttendanceRepository attendance; final FeeRepository fees; final PaymentRepository payments; final TestRepository tests; final ResultRepository results; final TimetableRepository timetable; final SubjectRepository subjects; final UserRepository users; final StudentTeacherAssignmentRepository studentTeacherAssignments; final IdService ids; final TrialGuard guard; final AuditService audit;
 ManagementController(StudentRepository s,TeacherRepository t,BatchRepository b,SessionRepository cs,AttendanceRepository a,FeeRepository f,PaymentRepository p,TestRepository te,ResultRepository r,TimetableRepository tt,SubjectRepository su,UserRepository u,StudentTeacherAssignmentRepository sta,IdService i,TrialGuard g,AuditService au){
   students=s;teachers=t;batches=b;sessions=cs;attendance=a;fees=f;payments=p;tests=te;results=r;timetable=tt;subjects=su;users=u;studentTeacherAssignments=sta;ids=i;guard=g;audit=au;
 }
 void tenantUser(){if(!(TenantContext.user().role()==Enums.Role.COACHING_ADMIN||TenantContext.user().role()==Enums.Role.TEACHER))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Access denied");guard.check(TenantContext.coachingId());}
 Teacher currentTeacher(){if(TenantContext.user().role()!=Enums.Role.TEACHER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher access required");return teachers.findByCoachingId(TenantContext.coachingId()).stream().filter(t->t.email().equalsIgnoreCase(TenantContext.user().email())).findFirst().orElseThrow(()->new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher profile not found"));}
 List<String> teacherBatchIds(){return currentTeacher().batchIds()==null?List.of():currentTeacher().batchIds();}
 List<Batch> assignedBatches(String coachingId){Set<String> ids=new HashSet<>(teacherBatchIds());return batches.findByCoachingId(coachingId).stream().filter(b->ids.contains(b.batchId())||(b.teacherIds()!=null&&b.teacherIds().contains(currentTeacher().teacherId()))).toList();}
 void adminOnly(){if(TenantContext.user().role()!=Enums.Role.COACHING_ADMIN)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin access required");guard.check(TenantContext.coachingId());}
 <T> List<T> page(List<T> values,int page,int size){int from=Math.max(0,page)*Math.max(1,size);if(from>=values.size())return List.of();return values.subList(from,Math.min(from+Math.max(1,size),values.size()));}

 @GetMapping("/dashboard") public Map<String,Object> dashboard(){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()==Enums.Role.TEACHER)return teacherDashboard(c);List<Student> studentDocs=students.findByCoachingId(c);List<FeeStructure> feeDocs=fees.findByCoachingId(c);double totalFees=feeDocs.stream().mapToDouble(FeeStructure::totalAmount).sum();double paidFees=payments.findByCoachingId(c).stream().mapToDouble(FeePayment::amount).sum();List<Attendance> attendanceDocs=attendance.findByCoachingIdOrderByDateDesc(c);Map<String,Object> result=new LinkedHashMap<>();result.put("students",studentDocs.size());result.put("activeStudents",studentDocs.stream().filter(s->"ACTIVE".equals(s.status())).count());result.put("teachers",teachers.countByCoachingId(c));result.put("batches",batches.countByCoachingId(c));result.put("todaySessions",sessions.findByCoachingIdAndDate(c,LocalDate.now()));result.put("fees",feeDocs);result.put("payments",payments.findByCoachingId(c));result.put("feesCollected",paidFees);result.put("feesPending",Math.max(0,totalFees-paidFees));result.put("attendanceToday",attendanceDocs.stream().filter(a->LocalDate.now().equals(a.date())).toList());result.put("attendance",attendanceDocs);result.put("tests",tests.findByCoachingId(c));return result;}

 @PostMapping("/teachers") public Map<String,Object> teacher(@Valid @RequestBody CreateTeacher r){
   requireAdmin(); String c=TenantContext.coachingId(); if(users.existsByEmail(r.email())) throw new IllegalArgumentException("Email already registered");
   String id=ids.next("TEA");String temp="Teach@"+UUID.randomUUID().toString().substring(0,8);
  var now=Instant.now();Teacher created=teachers.save(new Teacher(null,id,c,r.name(),r.email(),r.mobile(),r.subjects()==null?List.of():r.subjects(),r.batchIds()==null?List.of():r.batchIds(),"ACTIVE",now,now));
   String hash=new org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder().encode(temp);
  try{users.save(new User(null,r.email(),hash,Enums.Role.TEACHER,c,r.name(),r.mobile(),true,now,now));}catch(RuntimeException error){teachers.delete(created);throw error;}audit.record("TEACHER_CREATED","TEACHER",id);
   return Map.of("teacherId",id,"email",r.email(),"temporaryPassword",temp);
 }
 @GetMapping("/teachers") public List<Teacher> teachers(@RequestParam(defaultValue="")String search,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){tenantUser();String c=TenantContext.coachingId();List<Teacher> result=TenantContext.user().role()==Enums.Role.TEACHER?List.of(currentTeacher()):teachers.findByCoachingId(c);String term=search.trim().toLowerCase();if(!term.isEmpty())result=result.stream().filter(t->t.name().toLowerCase().contains(term)||t.email().toLowerCase().contains(term)||t.teacherId().toLowerCase().contains(term)).toList();return page(result,page,size);}
 @PutMapping("/teachers/{id}") public Teacher updateTeacher(@PathVariable String id,@RequestBody Map<String,Object> r){requireAdmin();String c=TenantContext.coachingId();Teacher t=teachers.findByTeacherIdAndCoachingId(id,c).orElseThrow();Object subjectsValue=r.get("subjects");List<String> subjects=subjectsValue instanceof List<?> values?values.stream().map(String::valueOf).toList():t.subjects();Object batchValue=r.get("batchIds");List<String> batchIds=batchValue instanceof List<?> values?values.stream().map(String::valueOf).toList():t.batchIds();if(batchIds.stream().anyMatch(batchId->batches.findByBatchIdAndCoachingId(batchId,c).isEmpty()))throw new IllegalArgumentException("Every assigned batch must belong to this coaching centre");return teachers.save(new Teacher(t.id(),t.teacherId(),t.coachingId(),(String)r.getOrDefault("name",t.name()),t.email(),(String)r.getOrDefault("mobile",t.mobile()),subjects,batchIds,(String)r.getOrDefault("status",t.status()),t.createdAt(),Instant.now()));}
 @DeleteMapping("/teachers/{id}") public void deleteTeacher(@PathVariable String id){requireAdmin();Teacher t=teachers.findByTeacherIdAndCoachingId(id,TenantContext.coachingId()).orElseThrow();teachers.delete(t);users.findByEmail(t.email()).ifPresent(users::delete);audit.record("TEACHER_DELETED","TEACHER",id);}

 @PostMapping("/batches") public Batch batch(@Valid @RequestBody CreateBatch r){adminOnly();String c=TenantContext.coachingId();List<String> teacherIds=r.teacherIds()==null?List.of():r.teacherIds();List<Teacher> assignedTeachers=teacherIds.stream().map(id->teachers.findByTeacherIdAndCoachingId(id,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre: "+id))).toList();if(assignedTeachers.stream().anyMatch(t->!"ACTIVE".equals(t.status())))throw new IllegalArgumentException("Inactive teachers cannot be assigned");var now=Instant.now();Batch created=batches.save(new Batch(null,ids.next("BATCH"),c,r.name(),r.course(),r.subjects()==null?List.of():r.subjects(),teacherIds,"ACTIVE",now,now));for(Teacher teacher:assignedTeachers){List<String> batchIds=new ArrayList<>(teacher.batchIds()==null?List.of():teacher.batchIds());if(!batchIds.contains(created.batchId()))batchIds.add(created.batchId());teachers.save(new Teacher(teacher.id(),teacher.teacherId(),teacher.coachingId(),teacher.name(),teacher.email(),teacher.mobile(),teacher.subjects(),batchIds,teacher.status(),teacher.createdAt(),now));}return created;}
 @GetMapping("/batches") public List<Batch> batchList(@RequestParam(defaultValue="")String search,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){tenantUser();String c=TenantContext.coachingId();List<Batch> result=TenantContext.user().role()==Enums.Role.TEACHER?assignedBatches(c):batches.findByCoachingId(c);String term=search.trim().toLowerCase();if(!term.isEmpty())result=result.stream().filter(b->b.name().toLowerCase().contains(term)||b.batchId().toLowerCase().contains(term)||b.course().toLowerCase().contains(term)).toList();return page(result,page,size);}

 @PostMapping("/subjects") public Subject createSubject(@Valid @RequestBody CreateSubject r){adminOnly();String c=TenantContext.coachingId();if(subjects.existsByCoachingIdAndCodeIgnoreCase(c,r.code()))throw new IllegalArgumentException("Subject code already exists");return subjects.save(new Subject(null,ids.next("SUB"),c,r.name(),r.code().trim().toUpperCase(),"ACTIVE",Instant.now(),Instant.now()));}
 @GetMapping("/subjects") public List<Subject> subjectList(){tenantUser();String c=TenantContext.coachingId();List<Subject> all=subjects.findByCoachingId(c);if(TenantContext.user().role()!=Enums.Role.TEACHER)return all;Set<String> allowed=new HashSet<>(currentTeacher().subjects()==null?List.of():currentTeacher().subjects());return all.stream().filter(s->allowed.contains(s.subjectId())||allowed.contains(s.code())||allowed.contains(s.name())).toList();}
 @PutMapping("/subjects/{id}") public Subject updateSubject(@PathVariable String id,@Valid @RequestBody CreateSubject r){adminOnly();String c=TenantContext.coachingId();Subject s=subjects.findBySubjectIdAndCoachingId(id,c).orElseThrow();if(!s.code().equalsIgnoreCase(r.code())&&subjects.existsByCoachingIdAndCodeIgnoreCase(c,r.code()))throw new IllegalArgumentException("Subject code already exists");return subjects.save(new Subject(s.id(),s.subjectId(),c,r.name(),r.code().trim().toUpperCase(),s.status(),s.createdAt(),Instant.now()));}
 @DeleteMapping("/subjects/{id}") public void deleteSubject(@PathVariable String id){adminOnly();subjects.delete(subjects.findBySubjectIdAndCoachingId(id,TenantContext.coachingId()).orElseThrow());}

 @PostMapping("/students") public Student student(@Valid @RequestBody CreateStudent r){adminOnly();String c=TenantContext.coachingId();validateBatch(c,r.batchId());var now=Instant.now();Student created=students.save(new Student(null,ids.next("STU"),c,r.name(),r.email(),r.mobile(),r.batchId(),"ACTIVE",now,now));if(r.subjectAssignments()!=null){for(Map<String,Object> assignment:r.subjectAssignments()){String subject=(String)assignment.get("subject");String teacherId=(String)assignment.get("teacherId");String batchId=(String)assignment.getOrDefault("batchId",r.batchId());if(subject==null||teacherId==null||batchId==null)continue;Teacher teacher=teachers.findByTeacherIdAndCoachingId(teacherId,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre"));if(!teacher.subjects().contains(subject))throw new IllegalArgumentException("Teacher is not assigned to that subject");if(!teacher.batchIds().contains(batchId))throw new IllegalArgumentException("Teacher is not assigned to that batch");String key=subject.trim();if(studentTeacherAssignments.existsByCoachingIdAndStudentIdAndTeacherIdAndBatchIdAndSubject(c,created.studentId(),teacherId,batchId,key))continue;studentTeacherAssignments.save(new StudentTeacherAssignment(null,ids.next("ASSIGN"),c,created.studentId(),teacherId,batchId,key,"ACTIVE",now,now));}}audit.record("STUDENT_CREATED","STUDENT",created.studentId());return created;}
 @GetMapping("/students") public List<Student> studentList(@RequestParam(defaultValue="")String search,@RequestParam(defaultValue="")String batchId,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="50")int size){tenantUser();String c=TenantContext.coachingId();List<Student> result;if(TenantContext.user().role()!=Enums.Role.TEACHER){result=students.findByCoachingId(c);}else{List<String> studentIds=studentTeacherAssignments.findByCoachingIdAndTeacherId(c,currentTeacher().teacherId()).stream().map(StudentTeacherAssignment::studentId).distinct().toList();result=students.findByCoachingId(c).stream().filter(s->studentIds.contains(s.studentId())).toList();}String term=search.trim().toLowerCase();if(!term.isEmpty())result=result.stream().filter(s->s.name().toLowerCase().contains(term)||s.studentId().toLowerCase().contains(term)||s.mobile().toLowerCase().contains(term)).toList();if(!batchId.isBlank())result=result.stream().filter(s->batchId.equals(s.batchId())).toList();return page(result,page,size);}
 @GetMapping("/teacher/me/students") public List<Student> teacherMyStudents(){tenantUser();if(TenantContext.user().role()!=Enums.Role.TEACHER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher access required");String c=TenantContext.coachingId();String teacherId=currentTeacher().teacherId();List<String> studentIds=studentTeacherAssignments.findByCoachingIdAndTeacherId(c,teacherId).stream().map(StudentTeacherAssignment::studentId).distinct().toList();return students.findByCoachingId(c).stream().filter(s->studentIds.contains(s.studentId())).toList();}
 @GetMapping("/teacher/me/classes") public List<Map<String,Object>> teacherMyClasses(){tenantUser();if(TenantContext.user().role()!=Enums.Role.TEACHER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher access required");String c=TenantContext.coachingId();String teacherId=currentTeacher().teacherId();return sessions.findByCoachingId(c).stream().filter(s->s.teacherId().equals(teacherId)).map(s->{List<StudentTeacherAssignment> assignments=studentTeacherAssignments.findByCoachingIdAndTeacherIdAndSubject(c,teacherId,s.subject());long count=assignments.stream().filter(a->a.batchId().equals(s.batchId())).map(StudentTeacherAssignment::studentId).distinct().count();Map<String,Object> m=new LinkedHashMap<>();m.put("session",s);m.put("studentCount",count);return m;}).toList();}
 @GetMapping("/teacher/me/sessions") public List<ClassSession> teacherMySessions(){tenantUser();if(TenantContext.user().role()!=Enums.Role.TEACHER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher access required");String c=TenantContext.coachingId();String teacherId=currentTeacher().teacherId();return sessions.findByCoachingId(c).stream().filter(s->s.teacherId().equals(teacherId)).toList();}
 @PutMapping("/students/{id}") public Student updateStudent(@PathVariable String id,@RequestBody Map<String,Object> r){adminOnly();String c=TenantContext.coachingId();Student s=students.findByStudentIdAndCoachingId(id,c).orElseThrow();String batchId=(String)r.getOrDefault("batchId",s.batchId());validateBatch(c,batchId);return students.save(new Student(s.id(),s.studentId(),c,(String)r.getOrDefault("name",s.name()),s.email(),(String)r.getOrDefault("mobile",s.mobile()),batchId,(String)r.getOrDefault("status",s.status()),s.createdAt(),Instant.now()));}
 @DeleteMapping("/students/{id}") public void deleteStudent(@PathVariable String id){requireAdmin();Student s=students.findByStudentIdAndCoachingId(id,TenantContext.coachingId()).orElseThrow();students.delete(s);audit.record("STUDENT_DELETED","STUDENT",id);}

 void validateBatch(String coachingId,String batchId){if(batchId!=null&&!batchId.isBlank())batches.findByBatchIdAndCoachingId(batchId,coachingId).orElseThrow(()->new IllegalArgumentException("Batch not found in this coaching centre"));}
 @PutMapping("/batches/{id}") public Batch updateBatch(@PathVariable String id,@RequestBody Map<String,Object> r){adminOnly();String c=TenantContext.coachingId();Batch b=batches.findByBatchIdAndCoachingId(id,c).orElseThrow();List<String> teacherIds=r.get("teacherIds") instanceof List<?> values?values.stream().map(String::valueOf).toList():b.teacherIds();teacherIds.forEach(x->teachers.findByTeacherIdAndCoachingId(x,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre")));return batches.save(new Batch(b.id(),b.batchId(),c,(String)r.getOrDefault("name",b.name()),(String)r.getOrDefault("course",b.course()),b.subjects(),teacherIds,(String)r.getOrDefault("status",b.status()),b.createdAt(),Instant.now()));}
 @DeleteMapping("/batches/{id}") public void deleteBatch(@PathVariable String id){adminOnly();batches.delete(batches.findByBatchIdAndCoachingId(id,TenantContext.coachingId()).orElseThrow());}
 @PostMapping("/batches/{id}/students") public Batch assignStudents(@PathVariable String id,@RequestBody Map<String,Object> body){adminOnly();String c=TenantContext.coachingId();Batch batch=batches.findByBatchIdAndCoachingId(id,c).orElseThrow();List<String> studentIds=body.get("studentIds") instanceof List<?> values?values.stream().map(String::valueOf).toList():List.of();studentIds.forEach(studentId->{Student student=students.findByStudentIdAndCoachingId(studentId,c).orElseThrow(()->new IllegalArgumentException("Student not found in this coaching centre"));students.save(new Student(student.id(),student.studentId(),c,student.name(),student.email(),student.mobile(),batch.batchId(),student.status(),student.createdAt(),Instant.now()));});return batch;}

 @PostMapping("/student-teacher-assignments") public StudentTeacherAssignment createAssignment(@Valid @RequestBody Map<String,Object> body){requireAdmin();String c=TenantContext.coachingId();String studentId=(String)body.get("studentId");String teacherId=(String)body.get("teacherId");String batchId=(String)body.get("batchId");String subject=(String)body.get("subject");if(studentId==null||teacherId==null||batchId==null||subject==null)throw new IllegalArgumentException("Missing assignment fields");students.findByStudentIdAndCoachingId(studentId,c).orElseThrow(()->new IllegalArgumentException("Student not found in this coaching centre"));Teacher teacher=teachers.findByTeacherIdAndCoachingId(teacherId,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre"));Batch batch=batches.findByBatchIdAndCoachingId(batchId,c).orElseThrow(()->new IllegalArgumentException("Batch not found in this coaching centre"));if(!teacher.subjects().contains(subject))throw new IllegalArgumentException("Teacher is not assigned to that subject");if(!teacher.batchIds().contains(batchId))throw new IllegalArgumentException("Teacher is not assigned to that batch");if(studentTeacherAssignments.existsByCoachingIdAndStudentIdAndTeacherIdAndBatchIdAndSubject(c,studentId,teacherId,batchId,subject))throw new IllegalArgumentException("Duplicate assignment rejected");var now=Instant.now();return studentTeacherAssignments.save(new StudentTeacherAssignment(null,ids.next("ASSIGN"),c,studentId,teacherId,batchId,subject,"ACTIVE",now,now));}
 @GetMapping("/student-teacher-assignments/student/{studentId}") public List<StudentTeacherAssignment> studentAssignments(@PathVariable String studentId){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()==Enums.Role.TEACHER){String teacherId=currentTeacher().teacherId();return studentTeacherAssignments.findByCoachingIdAndStudentId(c,studentId).stream().filter(a->a.teacherId().equals(teacherId)).toList();}students.findByStudentIdAndCoachingId(studentId,c).orElseThrow(()->new IllegalArgumentException("Student not found in this coaching centre"));return studentTeacherAssignments.findByCoachingIdAndStudentId(c,studentId);}
 @GetMapping("/student-teacher-assignments/teacher/{teacherId}") public List<StudentTeacherAssignment> teacherAssignments(@PathVariable String teacherId){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()==Enums.Role.TEACHER && !currentTeacher().teacherId().equals(teacherId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher can only query their own assignments");teachers.findByTeacherIdAndCoachingId(teacherId,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre"));return studentTeacherAssignments.findByCoachingIdAndTeacherId(c,teacherId);}
 @PutMapping("/student-teacher-assignments/{assignmentId}") public StudentTeacherAssignment updateAssignment(@PathVariable String assignmentId,@RequestBody Map<String,Object> body){requireAdmin();String c=TenantContext.coachingId();StudentTeacherAssignment assignment=studentTeacherAssignments.findById(assignmentId).orElseThrow(()->new IllegalArgumentException("Assignment not found"));if(!assignment.coachingId().equals(c))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Assignment does not belong to this coaching centre");String teacherId=(String)body.getOrDefault("teacherId",assignment.teacherId());String subject=(String)body.getOrDefault("subject",assignment.subject());String batchId=(String)body.getOrDefault("batchId",assignment.batchId());Teacher teacher=teachers.findByTeacherIdAndCoachingId(teacherId,c).orElseThrow(()->new IllegalArgumentException("Teacher not found in this coaching centre"));if(!teacher.subjects().contains(subject))throw new IllegalArgumentException("Teacher is not assigned to that subject");if(!teacher.batchIds().contains(batchId))throw new IllegalArgumentException("Teacher is not assigned to that batch");StudentTeacherAssignment updated=new StudentTeacherAssignment(assignment.id(),assignment.assignmentId(),assignment.coachingId(),assignment.studentId(),teacherId,batchId,subject,"ACTIVE",assignment.createdAt(),Instant.now());return studentTeacherAssignments.save(updated);}
 @DeleteMapping("/student-teacher-assignments/{assignmentId}") public void deleteAssignment(@PathVariable String assignmentId){requireAdmin();String c=TenantContext.coachingId();StudentTeacherAssignment assignment=studentTeacherAssignments.findById(assignmentId).orElseThrow(()->new IllegalArgumentException("Assignment not found"));if(!assignment.coachingId().equals(c))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Assignment does not belong to this coaching centre");studentTeacherAssignments.delete(assignment);}

 @PostMapping("/sessions") public ClassSession session(@Valid @RequestBody CreateSession r){adminOnly();String c=TenantContext.coachingId();Batch batch=batches.findByBatchIdAndCoachingId(r.batchId(),c).orElseThrow(()->new IllegalArgumentException("Batch not found"));Teacher teacher=teachers.findByTeacherIdAndCoachingId(r.teacherId(),c).orElseThrow(()->new IllegalArgumentException("Teacher not found"));if((batch.teacherIds()==null||!batch.teacherIds().contains(teacher.teacherId()))&&(teacher.batchIds()==null||!teacher.batchIds().contains(batch.batchId())))throw new IllegalArgumentException("Teacher is not assigned to this batch");var now=Instant.now();return sessions.save(new ClassSession(null,ids.next("SESSION"),c,r.batchId(),r.teacherId(),r.subject(),r.date(),r.startTime(),r.endTime(),"SCHEDULED",now,now));}
 @GetMapping("/sessions") public List<ClassSession> sessionList(){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()!=Enums.Role.TEACHER)return sessions.findByCoachingId(c);return sessions.findByCoachingId(c).stream().filter(s->s.teacherId().equals(currentTeacher().teacherId())).toList();}

 @PostMapping("/attendance/{sessionId}") public Attendance mark(@PathVariable String sessionId,@Valid @RequestBody AttendanceRequest r){
  tenantUser();String c=TenantContext.coachingId();ClassSession s=sessions.findBySessionIdAndCoachingId(sessionId,c).orElseThrow();if(TenantContext.user().role()==Enums.Role.TEACHER&&!s.teacherId().equals(currentTeacher().teacherId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You are not assigned to this session");
  Set<String> validStudentIds=studentTeacherAssignments.findByCoachingIdAndTeacherId(c,s.teacherId()).stream().filter(a->a.batchId().equals(s.batchId())&&a.subject().equalsIgnoreCase(s.subject())).map(StudentTeacherAssignment::studentId).collect(Collectors.toSet());
  List<Student> roster=students.findByCoachingId(c).stream().filter(x->s.batchId().equals(x.batchId())&&"ACTIVE".equals(x.status())&&validStudentIds.contains(x.studentId())).toList();
  Map<String,Map<String,String>> submitted=new LinkedHashMap<>();for(Map<String,String> item:r.students()){String studentId=item.get("studentId");String status=item.get("status");if(studentId==null||status==null||!Set.of("PRESENT","ABSENT","LATE").contains(status)||submitted.put(studentId,item)!=null)throw new IllegalArgumentException("Attendance must contain unique valid statuses");if(!validStudentIds.contains(studentId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Student is not assigned to this teacher for this session");}if(submitted.size()!=roster.size()||roster.stream().anyMatch(x->!submitted.containsKey(x.studentId())))throw new IllegalArgumentException("Attendance must include every active student assigned to this teacher for this session");
  var doc=attendance.findBySessionIdAndCoachingId(sessionId,c).map(a->new Attendance(a.id(),a.attendanceId(),c,sessionId,s.batchId(),s.date(),s.teacherId(),new ArrayList<>(submitted.values()),Instant.now()))
    .orElse(new Attendance(null,ids.next("ATT"),c,sessionId,s.batchId(),s.date(),s.teacherId(),new ArrayList<>(submitted.values()),Instant.now()));
  Attendance saved=attendance.save(doc);audit.record("ATTENDANCE_UPDATED","ATTENDANCE",saved.attendanceId());return saved;
 }
 String findTeacherBusinessId(String email,String c){return teachers.findByCoachingId(c).stream().filter(t->t.email().equalsIgnoreCase(email)).map(Teacher::teacherId).findFirst().orElse("");}
 @GetMapping("/attendance/report") public List<Attendance> report(@RequestParam(defaultValue="")String date,@RequestParam(defaultValue="")String batchId,@RequestParam(defaultValue="")String teacherId){tenantUser();String c=TenantContext.coachingId();List<Attendance> result;if(TenantContext.user().role()!=Enums.Role.TEACHER)result=attendance.findByCoachingIdOrderByDateDesc(c);else{Set<String> ids=sessions.findByCoachingId(c).stream().filter(s->s.teacherId().equals(currentTeacher().teacherId())).map(ClassSession::sessionId).collect(java.util.stream.Collectors.toSet());result=attendance.findByCoachingIdOrderByDateDesc(c).stream().filter(a->ids.contains(a.sessionId())).toList();}if(!date.isBlank())result=result.stream().filter(a->date.equals(a.date().toString())).toList();if(!batchId.isBlank())result=result.stream().filter(a->batchId.equals(a.batchId())).toList();if(!teacherId.isBlank())result=result.stream().filter(a->teacherId.equals(a.teacherId())).toList();return result;}

 @GetMapping("/teacher/dashboard") public Map<String,Object> teacherDashboard(){tenantUser();if(TenantContext.user().role()!=Enums.Role.TEACHER)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Teacher access required");return teacherDashboard(TenantContext.coachingId());}
 Map<String,Object> teacherDashboard(String coachingId){Teacher teacher=currentTeacher();List<Batch> assigned=assignedBatches(coachingId);Set<String> batchIds=assigned.stream().map(Batch::batchId).collect(java.util.stream.Collectors.toSet());List<Student> roster=students.findByCoachingId(coachingId).stream().filter(s->batchIds.contains(s.batchId())).toList();List<ClassSession> ownSessions=sessions.findByCoachingId(coachingId).stream().filter(s->s.teacherId().equals(teacher.teacherId())).toList();return Map.of("teacher",teacher,"batches",assigned,"students",roster,"sessions",ownSessions,"attendance",attendance.findByCoachingIdOrderByDateDesc(coachingId).stream().filter(a->a.teacherId().equals(teacher.teacherId())).toList(),"tests",tests.findByCoachingId(coachingId).stream().filter(t->teacher.teacherId().equals(t.teacherId())).toList(),"timetable",timetable.findByCoachingId(coachingId).stream().filter(t->teacher.teacherId().equals(t.teacherId())).toList());}

 @PostMapping("/fees") public FeeStructure fee(@Valid @RequestBody CreateFee r){adminOnly();String c=TenantContext.coachingId();students.findByStudentIdAndCoachingId(r.studentId(),c).orElseThrow();var now=Instant.now();return fees.save(new FeeStructure(null,ids.next("FEE"),c,r.studentId(),r.totalAmount(),r.installments(),"PENDING",now,now));}
 @GetMapping("/fees") public List<Map<String,Object>> feeList(){adminOnly();String c=TenantContext.coachingId();return fees.findByCoachingId(c).stream().map(f->{double paid=payments.findByFeeIdAndCoachingId(f.feeId(),c).stream().mapToDouble(FeePayment::amount).sum();String st=paid<=0?"PENDING":paid>=f.totalAmount()?"PAID":"PARTIAL";return Map.<String,Object>of("fee",f,"paid",paid,"pending",Math.max(0,f.totalAmount()-paid),"status",st);}).toList();}
 @PostMapping("/fees/{feeId}/payments") public FeePayment payment(@PathVariable String feeId,@Valid @RequestBody PaymentRequest r){adminOnly();String c=TenantContext.coachingId();FeeStructure f=fees.findByFeeIdAndCoachingId(feeId,c).orElseThrow();double paid=payments.findByFeeIdAndCoachingId(feeId,c).stream().mapToDouble(FeePayment::amount).sum();if(paid+r.amount()>f.totalAmount())throw new IllegalArgumentException("Payment exceeds outstanding amount");return payments.save(new FeePayment(null,ids.next("PAY"),c,feeId,r.amount(),r.paymentDate(),r.mode(),r.reference(),Instant.now()));}

 @PostMapping("/tests") public Test test(@Valid @RequestBody CreateTest r){tenantUser();String c=TenantContext.coachingId();Batch batch=batches.findByBatchIdAndCoachingId(r.batchId(),c).orElseThrow(()->new IllegalArgumentException("Batch not found"));String teacherId = TenantContext.user().role()==Enums.Role.TEACHER ? currentTeacher().teacherId() : "";if(TenantContext.user().role()==Enums.Role.TEACHER){if(!assignedBatches(c).stream().anyMatch(x->x.batchId().equals(batch.batchId())))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You are not assigned to this batch");if(!studentTeacherAssignments.findByCoachingIdAndTeacherIdAndSubject(c,teacherId,r.subject()).stream().anyMatch(a->a.batchId().equals(batch.batchId())))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not teach this subject in this batch");}var now=Instant.now();return tests.save(new Test(null,ids.next("TEST"),c,r.batchId(),teacherId,r.title(),r.subject(),r.testDate(),r.totalMarks(),now,now));}
 @GetMapping("/tests") public List<Test> testList(){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()!=Enums.Role.TEACHER)return tests.findByCoachingId(c);String teacher=currentTeacher().teacherId();return tests.findByCoachingId(c).stream().filter(x->teacher.equals(x.teacherId())).toList();}
 @PostMapping("/tests/{testId}/results") public List<TestResult> result(@PathVariable String testId,@Valid @RequestBody ResultRequest r){tenantUser();String c=TenantContext.coachingId();Test t=tests.findByTestIdAndCoachingId(testId,c).orElseThrow();if(TenantContext.user().role()==Enums.Role.TEACHER&&!currentTeacher().teacherId().equals(t.teacherId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not manage this test");Set<String> validStudents=studentTeacherAssignments.findByCoachingIdAndTeacherId(c,t.teacherId()).stream().filter(a->a.batchId().equals(t.batchId())&&a.subject().equalsIgnoreCase(t.subject())).map(StudentTeacherAssignment::studentId).collect(Collectors.toSet());List<TestResult> out=new ArrayList<>();for(var x:r.results()){String sid=String.valueOf(x.get("studentId"));if(!validStudents.contains(sid))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Student is not assigned to this teacher for this test");double marks=Double.parseDouble(String.valueOf(x.get("marks")));double pct=marks*100.0/t.totalMarks();String grade=pct>=90?"A+":pct>=80?"A":pct>=70?"B":pct>=60?"C":pct>=50?"D":"F";out.add(results.save(new TestResult(null,ids.next("RES"),c,testId,sid,marks,pct,grade,Instant.now())));}return out;}
 @GetMapping("/tests/{testId}/results") public List<TestResult> resultList(@PathVariable String testId){tenantUser();String c=TenantContext.coachingId();Test t=tests.findByTestIdAndCoachingId(testId,c).orElseThrow();if(TenantContext.user().role()==Enums.Role.TEACHER&&!currentTeacher().teacherId().equals(t.teacherId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not manage this test");return results.findByTestIdAndCoachingId(testId,c);}

 @PostMapping("/timetable") public Timetable timetable(@Valid @RequestBody CreateTimetable r){adminOnly();String c=TenantContext.coachingId();Batch batch=batches.findByBatchIdAndCoachingId(r.batchId(),c).orElseThrow(()->new IllegalArgumentException("Batch not found"));Teacher teacher=teachers.findByTeacherIdAndCoachingId(r.teacherId(),c).orElseThrow(()->new IllegalArgumentException("Teacher not found"));if((batch.teacherIds()==null||!batch.teacherIds().contains(teacher.teacherId()))&&(teacher.batchIds()==null||!teacher.batchIds().contains(batch.batchId())))throw new IllegalArgumentException("Teacher is not assigned to this batch");if(!studentTeacherAssignments.findByCoachingIdAndTeacherIdAndSubject(c,teacher.teacherId(),r.subject()).stream().anyMatch(a->a.batchId().equals(batch.batchId())))throw new IllegalArgumentException("Teacher is not assigned to this subject in this batch");var now=Instant.now();return this.timetable.save(new Timetable(null,ids.next("TT"),c,r.batchId(),r.teacherId(),r.subject(),r.dayOfWeek(),r.startTime(),r.endTime(),r.room(),now,now));}
 @GetMapping("/timetable") public List<Timetable> timetableList(){tenantUser();String c=TenantContext.coachingId();if(TenantContext.user().role()!=Enums.Role.TEACHER)return timetable.findByCoachingId(c);String teacher=currentTeacher().teacherId();return timetable.findByCoachingId(c).stream().filter(x->teacher.equals(x.teacherId())).toList();}

 void requireAdmin(){if(TenantContext.user().role()!=Enums.Role.COACHING_ADMIN)throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin access required");guard.check(TenantContext.coachingId());}
}
