import {Component,inject} from '@angular/core'; import {CommonModule} from '@angular/common'; import {FormsModule} from '@angular/forms'; import {ApiService} from '../core/api.service';
@Component({standalone:true,imports:[CommonModule,FormsModule],template:`<div class="page"><div class="section-head"><div><div class="eyebrow">DAILY OPERATIONS</div><h1>Operations</h1></div></div><div class="tabs"><button (click)="tab='batches'">Batches</button><button (click)="tab='sessions'">Sessions</button><button (click)="tab='attendance'">Attendance</button><button (click)="tab='fees'">Fees</button><button (click)="tab='tests'">Tests</button><button (click)="tab='timetable'">Timetable</button></div>
<div class="panel" *ngIf="tab==='batches'"><h3>Create batch</h3><form (ngSubmit)="createBatch()" class="grid2"><input name="bn" [(ngModel)]="batch.name" placeholder="Batch name" required><input name="course" [(ngModel)]="batch.course" placeholder="Course" required><input name="subjects" [(ngModel)]="batch.subjectsText" placeholder="Subjects"><input name="teacherIds" [(ngModel)]="batch.teacherIdsText" placeholder="Teacher IDs, comma separated"><button class="primary">Create</button></form><div class="row" *ngFor="let b of batches"><b>{{b.name}}</b><span>{{b.course}}</span><span>{{b.batchId}}</span><span>{{b.teacherIds?.join(', ')}}</span></div></div>
<div class="panel" *ngIf="tab==='sessions'"><h3>Create class session</h3><form (ngSubmit)="createSession()" class="grid2"><input name="batchId" [(ngModel)]="session.batchId" placeholder="Batch ID" required><input name="teacherId" [(ngModel)]="session.teacherId" placeholder="Teacher ID" required><input name="subject" [(ngModel)]="session.subject" placeholder="Subject" required><input name="date" [(ngModel)]="session.date" type="date" required><input name="start" [(ngModel)]="session.startTime" placeholder="10:00" required><input name="end" [(ngModel)]="session.endTime" placeholder="11:00" required><button class="primary">Schedule class</button></form><div class="row" *ngFor="let s of sessions"><span>{{s.sessionId}}</span><span>{{s.subject}}</span><span>{{s.date}} {{s.startTime}}</span></div></div>
<div class="panel" *ngIf="tab==='attendance'"><h3>Mark attendance</h3><p class="muted">Enter session ID and student statuses as JSON.</p><input [(ngModel)]="attendanceSession" placeholder="Session ID"><textarea [(ngModel)]="attendanceJson" rows="5" placeholder='[{"studentId":"STU_000001","status":"PRESENT"}]'></textarea><button class="primary" (click)="markAttendance()">Save attendance</button><div class="row" *ngFor="let a of attendance"><span>{{a.date}}</span><span>{{a.sessionId}}</span><span>{{a.students?.length}} students</span></div></div>
<div class="panel" *ngIf="tab==='fees'"><h3>Create fee</h3><form (ngSubmit)="createFee()" class="grid2"><input name="sid" [(ngModel)]="fee.studentId" placeholder="Student ID" required><input name="amount" [(ngModel)]="fee.totalAmount" type="number" placeholder="Total amount" required><textarea name="inst" [(ngModel)]="fee.installmentsJson" rows="5" placeholder='[{"name":"Installment 1","amount":10000,"dueDate":"2026-10-01"}]'></textarea><button class="primary">Create fee</button></form><div class="row" *ngFor="let f of fees"><span>{{f.fee?.feeId}}</span><span>₹{{f.fee?.totalAmount}}</span><span>Paid ₹{{f.paid}}</span><span>{{f.status}}</span></div></div>
<div class="panel" *ngIf="tab==='tests'"><h3>Create test</h3><form (ngSubmit)="createTest()" class="grid2"><input name="title" [(ngModel)]="test.title" placeholder="Title" required><input name="batch" [(ngModel)]="test.batchId" placeholder="Batch ID" required><input name="subject" [(ngModel)]="test.subject" placeholder="Subject" required><input name="date" [(ngModel)]="test.testDate" type="date" required><input name="marks" [(ngModel)]="test.totalMarks" type="number" placeholder="Total marks" required><button class="primary">Create test</button></form><div class="row" *ngFor="let t of tests"><span>{{t.testId}}</span><span>{{t.title}}</span><span>{{t.totalMarks}}</span></div></div>
<div class="panel" *ngIf="tab==='timetable'"><h3>Create timetable entry</h3><form (ngSubmit)="createTT()" class="grid2"><input name="batch" [(ngModel)]="tt.batchId" placeholder="Batch ID" required><input name="teacher" [(ngModel)]="tt.teacherId" placeholder="Teacher ID" required><input name="subject" [(ngModel)]="tt.subject" placeholder="Subject" required><input name="day" [(ngModel)]="tt.dayOfWeek" placeholder="MONDAY" required><input name="start" [(ngModel)]="tt.startTime" placeholder="10:00" required><input name="end" [(ngModel)]="tt.endTime" placeholder="11:00" required><input name="room" [(ngModel)]="tt.room" placeholder="Room"><button class="primary">Save timetable</button></form><div class="row" *ngFor="let x of timetable"><span>{{x.dayOfWeek}}</span><span>{{x.subject}}</span><span>{{x.startTime}} - {{x.endTime}}</span></div></div></div>`})
export class OperationsComponent{api=inject(ApiService);tab='batches';batches:any[]=[];sessions:any[]=[];attendance:any[]=[];fees:any[]=[];tests:any[]=[];timetable:any[]=[];batch:any={};session:any={};fee:any={};test:any={};tt:any={};attendanceSession='';attendanceJson='[]';ngOnInit(){this.load()}
load(){this.api.get<any[]>('/batches').subscribe(x=>this.batches=x);this.api.get<any[]>('/sessions').subscribe(x=>this.sessions=x);this.api.get<any[]>('/attendance/report').subscribe(x=>this.attendance=x);this.api.get<any[]>('/fees').subscribe(x=>this.fees=x);this.api.get<any[]>('/tests').subscribe(x=>this.tests=x);this.api.get<any[]>('/timetable').subscribe(x=>this.timetable=x)}
createBatch(){this.api.post('/batches',{name:this.batch.name,course:this.batch.course,subjects:(this.batch.subjectsText||'').split(',').map((x:string)=>x.trim()).filter(Boolean),teacherIds:(this.batch.teacherIdsText||'').split(',').map((x:string)=>x.trim()).filter(Boolean)}).subscribe(()=>{this.batch={};this.load()})}
createSession(){this.api.post('/sessions',this.session).subscribe(()=>{this.session={};this.load()})}
markAttendance(){this.api.post('/attendance/'+this.attendanceSession,{students:JSON.parse(this.attendanceJson)}).subscribe(()=>this.load())}
createFee(){this.api.post('/fees',{studentId:this.fee.studentId,totalAmount:+this.fee.totalAmount,installments:JSON.parse(this.fee.installmentsJson||'[]')}).subscribe(()=>{this.fee={};this.load()})}
createTest(){this.api.post('/tests',this.test).subscribe(()=>{this.test={};this.load()})}
createTT(){this.api.post('/timetable',this.tt).subscribe(()=>{this.tt={};this.load()})}}
